website/rosenext/apps/user/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import include, path

from apps.user.views import oauth_profile, ProfileView

app_name = "users"

urlpatterns = [
    path("oauth/profile/", oauth_profile, name="oauth_profile"),
    path("profile/", login_required(ProfileView.as_view()), name="profile"),
]

website/rosenext/rosenext/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

import oauth2_provider.views as oauth2_views

import apps.user

oauth2_endpoint_views = [
    path("authorize/", oauth2_views.AuthorizationView.as_view(), name="authorize"),
    path("token/", oauth2_views.TokenView.as_view(), name="token"),
    path("revoke-token/", oauth2_views.RevokeTokenView.as_view(), name="revoke-token"),
]

urlpatterns = [
    path("", TemplateView.as_view(template_name="home.html")),
    path("account/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    path("oauth/", include((oauth2_endpoint_views, "oauth"))),
    path("user/", include("apps.user.urls", namespace="user")),
]

website/rosenext/apps/user/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class RoseNextUser(AbstractUser):
    pass

website/rosenext/apps/user/views.py
import json

from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponse
from django.views.generic import TemplateView


@login_required()
def oauth_profile(request, *args, **kwargs):
    user_info = {
        "id": request.user.id,
        "name": f"{request.user.username}",
        "email": request.user.email,
    }
    return HttpResponse(json.dumps(user_info), status=200)


class ProfileView(TemplateView):
    template_name = "user/profile.html"

website/rosenext/templates/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title_detail %}{% endblock %}{% if not request.path == "/"%} | {% endif %}{{ settings.SITE_NAME }}
    </title>

    {% if settings.DEBUG %}
    <link rel="stylesheet" href="{% static "vendor/bulma-0.9.0/bulma.css" %}">
    <link rel="stylesheet" href="{% static "vendor/fork-awesome-1.1.7/css/fork-awesome.css" %}">
    {% else %}
    <link rel="stylesheet" href="{% static "vendor/bulma-0.9.0/bulma.min.css" %}">
    <link rel="stylesheet" href="{% static "vendor/fork-awesome-1.1.7/css/fork-awesome.min.css" %}">
    {% endif %}

    <link rel="stylesheet" href="{% static "app.css" %}">
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
    <link rel="icon" href="{% static 'favicon.ico' %}" type="image/x-icon">
</head>

<body>
    {% block body %}
    {% include "nav.html" %}

    {% if messages %}
    {% for message in messages %}
    <div class="notification {% if message.tags %}{{ message.tags }}{% endif %}">
        <button class="delete mt-4"></button>
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}

    <main class="main">
        {% block main %}
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        {% endblock %}
    </main>

    <script defer src="{%static "app.js" %}"></script>
    {% endblock %}
</body>

</html>

website/rosenext/templates/home.html
{% extends "base.html" %}

{% load i18n %}

{% block content %}
<section id="hero-main" class="hero is-link">
    <div class="hero-body">
        <div class="container">
            <h1 class="title">
                {% trans "Welcome to ROSE Next" %}
            </h1>
            <h2 class="subtitle">
                {% trans "A free-to-play MMORPG" %}
            </h2>
            <div>
                <a class="button is-primary" href="{{ settings.CLIENT_DOWNLOAD_URL }}">
                    <span class="icon"><i class="fa fa-download"></i></span>
                    <strong>{% trans "Download" %}</strong>
                </a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

website/rosenext/templates/nav.html
{% load i18n %}

<nav class="navbar is-dark" role="navigation" aria-label="main navigation">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="/">
                <!--<img src="" width="" height="">-->
                <b>ROSE Next</b>
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                data-target="navbar-main-menu">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbar-main-menu" class="navbar-menu">
            <div class="navbar-start">
                <a class="navbar-item" href="https://blog.rosenext.com" target="_blank">
                    {% trans "Blog" %}
                </a>
            </div>

            <div class="navbar-end">
                <a class="navbar-item" title="Discord" aria-label="Discord server link"
                    href="{{ settings.DISCORD_URL }}" target="_blank">
                    <span class="icon"><i class="fa fa-discord"></i></span>
                </a>
                {% if not user.is_authenticated %}
                <a class="navbar-item" href="{% url "account_login" %}">
                    {% trans "Sign in" %}
                </a>
                <div class="navbar-item">
                    <a class="button is-link is-inverted is-outlined" href="{% url "account_signup" %}">
                        {% trans "Sign up" %}
                    </a>
                </div>
                {% else %}
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">{{ user.username }}</a>
                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{% url "user:profile" %}">{% trans "My Account" %}</a>

                        {% if user.is_superuser %}
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{% url "admin:index" %}">Admin</a>
                        {% endif %}

                        <hr class="navbar-divider">
                        <form class="navbar-item" method="post" action="{% url "account_logout" %}">
                            {% csrf_token %}
                            <input type="submit" value="Sign Out" class="navbar-item" />
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}
        </div>
    </div>
    </div>
</nav>

website/rosenext/templates/user/base.html
{% extends "base.html" %}

{% block content %}
<section class="section">
    <div class="content">
        {% block user_content %}{% endblock %}
    </div>
</section>
{% endblock %}

website/rosenext/templates/user/profile.html
{% extends "user/base.html" %}

{% load i18n %}

{% block title_detail %}{{ request.user.username }}'s {% trans "Profile" %}{% endblock %}

{% block user_content %}
<h1>Profile: {{ request.user.username }}</h1>
<p class="subtitle">Manage</p>
<ul>
    <li><a href="{% url "account_change_password" %}">Change password</a></li>
    <li><a href="{% url "account_email" %}">Change email</a></li>
</ul>
{% endblock %}